# Generated by Django 4.2.18 on 2025-03-12 03:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnviFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="数据名称")),
                ("description", models.TextField(blank=True, verbose_name="数据描述")),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "hdr_file",
                    models.FileField(
                        upload_to="envi_files/%Y/%m/%d/", verbose_name="HDR文件"
                    ),
                ),
                (
                    "img_file",
                    models.FileField(
                        upload_to="envi_files/%Y/%m/%d/", verbose_name="IMG文件"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="下载次数"),
                ),
            ],
            options={
                "verbose_name": "ENVI文件",
                "verbose_name_plural": "ENVI文件",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="EnviData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="影像名称"
                    ),
                ),
                (
                    "file_path",
                    models.FilePathField(
                        max_length=255,
                        path="E:/graduation_bzy/data",
                        verbose_name="文件路径",
                    ),
                ),
                ("acquisition_date", models.DateField(verbose_name="获取时间")),
                (
                    "coordinate_system",
                    models.CharField(max_length=255, verbose_name="坐标系"),
                ),
                ("resolution", models.FloatField(verbose_name="分辨率(m)")),
                (
                    "bounds",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="空间范围"
                    ),
                ),
                (
                    "center_point",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="中心点"
                    ),
                ),
                ("bands_info", models.JSONField(verbose_name="波段信息")),
                (
                    "thumbnail",
                    models.ImageField(upload_to="thumbnails/", verbose_name="缩略图"),
                ),
                (
                    "tile_url",
                    models.CharField(
                        default="/static/tiles/default/{z}/{x}/{y}.png",
                        max_length=500,
                        verbose_name="瓦片URL",
                    ),
                ),
                (
                    "envi_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envi_data",
                        to="geodata.envifile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ENVI遥感数据",
                "verbose_name_plural": "ENVI遥感数据",
            },
        ),
    ]
