# Generated by Django 4.2.19 on 2025-03-13 08:44

from django.db import migrations, models
import geodata.models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envifile",
            name="hdr_file",
            field=models.FileField(
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="envi_files/%Y/%m/%d/",
                verbose_name="HDR文件",
            ),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="img_file",
            field=models.FileField(
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="envi_files/%Y/%m/%d/",
                verbose_name="IMG文件",
            ),
        ),
    ]
