# Generated by Django 4.2.19 on 2025-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0004_alter_envifile_fields_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="envidata",
            name="sensor_type",
            field=models.CharField(
                choices=[("S2", "Sentinel-2 多光谱"), ("GF5", "GF5 高光谱")],
                default="S2",
                max_length=10,
                verbose_name="传感器类型",
            ),
        ),
        migrations.AddField(
            model_name="envidata",
            name="wavelength_info",
            field=models.JSONField(blank=True, null=True, verbose_name="波长信息"),
        ),
    ]
