# Generated by Django 4.2.19 on 2025-03-14 09:44

from django.db import migrations

def update_existing_records(apps, schema_editor):
    EnviData = apps.get_model('geodata', 'EnviData')
    for data in EnviData.objects.all():
        # 根据波段数判断传感器类型
        bands_info = data.bands_info
        if bands_info:
            import json
            bands_info_dict = json.loads(bands_info)
            band_count = bands_info_dict.get('count', 0)
            data.sensor_type = 'GF5' if band_count > 10 else 'S2'
            data.save()

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_envidata_sensor_type_envidata_wavelength_info'),
    ]

    operations = [
        migrations.RunPython(update_existing_records, reverse_migration),
    ]
