# Generated by Django 4.2.19 on 2025-03-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0007_fix_sensor_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envidata",
            name="sensor_type",
            field=models.CharField(
                choices=[
                    ("S2", "Sentinel-2 多光谱"),
                    ("GF5", "GF5 高光谱"),
                    ("ASTER", "ASTER 多光谱"),
                    ("PRISMA", "PRISMA 高光谱"),
                ],
                default="S2",
                max_length=10,
                verbose_name="传感器类型",
            ),
        ),
    ]
