# Generated by Django 4.2.19 on 2025-03-20 11:31

from django.db import migrations, models
import django.utils.timezone
import geodata.models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0008_alter_envidata_sensor_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="envidata",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="envidata",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="envidata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="envidata",
            name="coordinate_system",
            field=models.CharField(max_length=500, verbose_name="坐标系"),
        ),
        migrations.AlterField(
            model_name="envidata",
            name="file_path",
            field=models.FilePathField(
                max_length=500, path="E:/graduation_bzy/data", verbose_name="文件路径"
            ),
        ),
        migrations.AlterField(
            model_name="envidata",
            name="name",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="影像名称"
            ),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="hdr_file",
            field=models.FileField(
                max_length=500,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="envi_files/%Y/%m/%d/",
                verbose_name="HDR文件",
            ),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="img_file",
            field=models.FileField(
                max_length=500,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="envi_files/%Y/%m/%d/",
                verbose_name="IMG文件",
            ),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="name",
            field=models.CharField(max_length=500, verbose_name="数据名称"),
        ),
        migrations.AlterModelTable(
            name="envidata",
            table="geodata_envidata",
        ),
    ]
