# Generated by Django 4.2.19 on 2025-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0009_alter_envidata_options_envidata_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envidata",
            name="thumbnail",
            field=models.ImageField(
                max_length=500, upload_to="thumbnails/", verbose_name="缩略图"
            ),
        ),
    ]
