# Generated by Django 4.2.19 on 2025-03-21 07:40

from django.db import migrations, models
import geodata.models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0010_alter_envidata_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="envifile",
            name="file_size",
        ),
        migrations.AddField(
            model_name="envifile",
            name="pc_hdr_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="alteration_files/",
                verbose_name="PC方法HDR文件",
            ),
        ),
        migrations.AddField(
            model_name="envifile",
            name="pc_img_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="alteration_files/",
                verbose_name="PC方法IMG文件",
            ),
        ),
        migrations.AddField(
            model_name="envifile",
            name="ratio_hdr_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="alteration_files/",
                verbose_name="Ratio方法HDR文件",
            ),
        ),
        migrations.AddField(
            model_name="envifile",
            name="ratio_img_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="alteration_files/",
                verbose_name="Ratio方法IMG文件",
            ),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="hdr_file",
            field=models.FileField(
                max_length=500,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="envi_files/",
                verbose_name="HDR文件",
            ),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="img_file",
            field=models.FileField(
                max_length=500,
                storage=geodata.models.KeepNameFileStorage(),
                upload_to="envi_files/",
                verbose_name="IMG文件",
            ),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="name",
            field=models.CharField(blank=True, max_length=500, verbose_name="文件名"),
        ),
        migrations.AlterField(
            model_name="envifile",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
        ),
    ]
