# Generated by Django 4.2.19 on 2025-03-24 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geodata", "0011_remove_envifile_file_size_envifile_pc_hdr_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工作站名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作站",
                "verbose_name_plural": "工作站",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkStationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "envi_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodata.envifile",
                        verbose_name="ENVI文件",
                    ),
                ),
                (
                    "workstation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodata.workstation",
                        verbose_name="工作站",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作站文件",
                "verbose_name_plural": "工作站文件",
                "ordering": ["-added_at"],
                "unique_together": {("workstation", "envi_file")},
            },
        ),
    ]
